# common values at global level. 
namespace: mtdp

# micro-service specific values inside each service subsection.
hello:
  image: 
    name: nginx
    tag: 'latest'
    pullpolicy: IfNotPresent
  container:
    port: 8080
    protocol: TCP
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 100Mi
  replicas: 1
  service:
      type: ClusterIP
      port: 80
  ingress:
      enabled: false
