# common values at global level. 
namespace: hello

# micro-service specific values inside each service subsection.
hello:
  image: 
    name: a5hut0sh/helloworld
    tag: '1.0'
    pullpolicy: IfNotPresent
  container:
    port: 8080
    protocol: TCP
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 100Mi
  replicas: 1
  service:
      type: ClusterIP
      port: 80
  ingress:
      enabled: false
  ServiceAccount:
      name: "prometheus-alertmanager"
